"""cascade deletes

Revision ID: d9fe0d3acbf1
Revises: 7e338fc0f8cf
Create Date: 2024-02-24 02:06:32.870015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9fe0d3acbf1"
down_revision: Union[str, None] = "7e338fc0f8cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.ForeignKeyConstraint(["predmet_id"], ["predmeti.id"], ondelete="CASCADE")
    sa.ForeignKeyConstraint(["korisnik_id"], ["users.id"], ondelete="CASCADE")
    sa.ForeignKeyConstraint(["predavanje_id"], ["predavanja.id"], ondelete="CASCADE")
    sa.ForeignKeyConstraint(["predmet_id"], ["predmeti.id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    sa.ForeignKeyConstraint(["predmet_id"], ["predmeti"]).drop()
    sa.ForeignKeyConstraint(["korisnik_id"], ["users"]).drop()
    sa.ForeignKeyConstraint(["predavanje_id"], ["predavanja"]).drop()
    sa.ForeignKeyConstraint(["predmet_id"], ["predmeti"]).drop()

    # ### end Alembic commands ###
